### PR TITLE
Keep comments on the same line when indenting. (trying to fix #100)

### LINKED ISSUE #100: Comments are displayed with a different indentation
Hi there!

When I inspect or edit the following shader:

```glsl
    precision highp float;
    
    uniform vec3 color; // ms({ value: '#ff0000' })
    uniform float brightness; // ms({ value: 0, range: [0, 0.5], step: 0.1 })
    uniform vec2 dummyValue; // ms({ value: [1024, 768], range: [[0, 2000], [0, 1500]] })
    uniform bool visible; // ms({ value: 1, name: 'Visibility' })
    uniform int test; // ms({ value: 0 })

    void main() {
      gl_FragColor = vec4(color + brightness, 1.0);
    }
```

is displayed like this:

Screen Shot 2019-04-05 at 11 56 00

and by consequence, after edited, the shader is broken.

### PR DESCRIPTION
**Pull request by luruke**
Hey @sebavan ,
this should fix #100.

Hope doesn't have side effects 😆

### CODE REVIEW

**Comment by sebavan** [comment]
Thanks a lot !!! I ll try it ASAP on some big use case and publish the plugin back this week end as the capture has now been migrated to React :-)

**Comment by sebavan** [comment]
At a first glance your change looks perfect, thanks a lot

**Comment by sebavan** [comment]
@luruke, it works great !!! do you need npm only for your project or the extensions to be deployed as well (cause it takes a bit more time ;-) )

**Comment by luruke** [comment]
Hello @sebavan , sorry for the late reply.
Yes please, I would need the extensions to be updated, but I understand that involves some more steps :)

**Comment by sebavan** [comment]
Ok, no problem, I ll do as soon as I ll be back home (currently in travel without the required access to publish) I ll be there end of next week.

Thanks for your patience, the fix works beautifully.

**Comment by luruke** [comment]
Thanks to you! Travel safe ✈️

**Comment by sebavan** [comment]
@luruke All pushed Thanks again for your patience

**Pull request merged**
