### PR TITLE
Fixes texture display when a uniforms is bound to a texture array

### PR DESCRIPTION
**Pull request by akarimgc**
- Adds correct parsing for the instance where a uniform is an array of textures.
- In this case we need to bind to values[].value for the texture unit.

### CODE REVIEW

**Comment by akarimgc** [comment]
> Thanks a ton !!! could you remove the dist built files from the PR and drop a line in the changelogs.md ?

Thanks @sebavan. Have removed the dist files and updated the changelogs with a new entry for `v0.9.29` not sure if that's what you meant.

**Comment by sebavan** [comment]
Oh sorry a last change :-( could you move the line in v0.9.28 ? this will be the next release :-) The doc is always one version in advance to prep the next release (agree it is not obvious) I ll merge right after

**Comment by akarimgc** [comment]
> Oh sorry a last change :-( could you move the line in v0.9.28 ? this will be the next release :-) The doc is always one version in advance to prep the next release (agree it is not obvious) I ll merge right after

Hey @sebavan moved the changelog entry. Took me a while to circle back!

**Comment by sebavan** [comment]
Perfect, thanks a lot !!!

**Pull request merged**
